name: 'Chantier 1045 de la Rivière, Québec'
favicon: null
layout_spectrum: 0.446552351815626
typography_spectrum: 0.48402045550756156
title: 'Suivi du chantier du 1045 de la rivière, Québec'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#547793'
    - '#2c4424'
    - '#000000'
    - '#a7aeb4'
    - '#1c941e'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
