name: 'Chantier 1045 de la Rivière, Québec'
favicon: null
layout_spectrum: 0.446552351815626
typography_spectrum: 0.48402045550756156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8013246364425868
  lightness: 0.8481493080034852
  saturation: 0.2663492592982948
  rhythmicContrast: 0.38255130941979587
purpose: []
