name: 'Chantier 1045 de la Rivière, Québec'
favicon: null
layout_spectrum: 0.63117
typography_spectrum: 0.44952
title: 'Suivi du chantier du 1045 de la rivière, Québec'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20202a'
    - '#444a56'
    - '#716f63'
    - '#9d9b8e'
    - '#898993'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
