typography_spectrum: 0.44952
color:
  brandColors:
    - '#20202a'
    - '#444a56'
    - '#716f63'
    - '#9d9b8e'
    - '#898993'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.27256
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Simon-Pierre jarry
  email: spjarry@gmail.com
name: 'Chantier 1045 de la Rivière, Québec'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Suivi du chantier du 1045 de la rivière, Québec'
purpose: []
